python:
  classical_ml:
    primary: "scikit-learn==1.3.2"
    dependencies:
      - "numpy==1.24.3"
      - "pandas==2.0.3"
      - "scipy==1.11.1"
  deep_learning:
    pytorch:
      version: "2.0.1"
      dependencies:
        - "torchvision==0.15.2"
        - "torchaudio==2.0.2"
    tensorflow:
      version: "2.13.1"
      dependencies:
        - "tensorboard==2.13.0"
  llm:
    transformers:
      version: "4.30.2"
      dependencies:
        - "tokenizers==0.13.3"
        - "datasets==2.14.4"

rust:
  classical_ml:
    linfa:
      version: "0.7.0"
      features: ["all"]
    smartcore:
      version: "0.3.2"
      features: ["all"]
  deep_learning:
    tch:
      version: "0.13.0"
      features: ["cuda"]
    burn:
      version: "0.14.0"
      features: ["cuda", "wgpu"]
    candle:
      version: "0.3.3"
      features: ["cuda", "cudnn"]
  llm:
    candle_transformers:
      version: "0.3.3"
    ort:
      version: "1.15.1"
      features: ["cuda"] 